/*
 * BPanel.java
 *
 * Created on July 21, 2004, 1:06 PM
 */

package org.netbeans.tests.examples.packc;

import java.awt.event.ActionListener;

/**
 *
 * @author  eh103527
 */
public class BPanel extends javax.swing.JPanel implements ActionListener {
    
    /** Creates new form BPanel */
    public BPanel() {
        initComponents();
    }

    public void actionPerformed(java.awt.event.ActionEvent e) {
        jButton1.getActionListeners()[0].actionPerformed(e);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        add(jButton1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
    
}
